version: "3.8"

volumes:
  rabbitmq_data:

services:

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: g10t4/app:esd
    ports:
      - "3001:3001"
    depends_on:
      - applicant
      - application
 
  #######################################
  # applicant: The Applicant microservice
  #######################################
  applicant:
    build:
      context: ./
      dockerfile: microservices/applicant/applicant.Dockerfile
    image: g10t4/applicant:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root${MYSQL_PASSWORD}@host.docker.internal:${MYSQL_PORT}/applicant_details
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000" 
 
  #####################################################
  # application: The Application microservice
  #####################################################
  application:
    build:
      context: ./
      dockerfile: microservices/application/application.Dockerfile
    image: g10t4/application:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root${MYSQL_PASSWORD}@host.docker.internal:${MYSQL_PORT}/application
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
  
  ####################################
  # payment: The payment microservice TBC
  ####################################
  # payment:
  #   build:
  #     context: ./
  #     dockerfile: microservices/payment/payment.Dockerfile
  #   image: g10t4/payment:esd
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://root${MYSQL_PASSWORD}@host.docker.internal:${MYSQL_PORT}/payment
  #     PYTHONUNBUFFERED: 1
  #   networks:
  #     - kong-net
  #   ports:
  #     - "5400:5400"

  ################################
  # RabbitMQ: The messaging broker   
  ################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  ##############################################
  # Activity Log: The Activity Log microservice
  ##############################################
  activity_log:
    build:
      context: ./
      dockerfile: microservices/activity_log/activity_log.Dockerfile
    image: g10t4/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1


  ###############################
  # Error: The Error microservice
  ################################
  error:
    build:
      context: ./
      dockerfile: microservices/error/error.Dockerfile
    image: g10t4/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1


  #########################################################
  # application_complex: The Submit Application microservice
  #########################################################
  application_complex:
    build:
      context: ./
      dockerfile: microservices/application_complex/application_complex.Dockerfile
    image: g10t4/application_complex:esd
    restart: always
    depends_on:
      - application
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      application_URL: http://application:5001/application
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  