version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # applicant: The Applicant microservice
  ###################################
  applicant:
    build:
      context: ./
      dockerfile: applicant.Dockerfile
    image: ideal97/applicant:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/applicant_details
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000" 
 
  #######################################################
  # application: The application microservice
  #######################################################
  application:
    build:
      context: ./
      dockerfile: application.Dockerfile
    image: ideal97/application:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/application
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  #######################################################
  # admin_cost: The admin_cost microservice
  #######################################################
  admin_cost:
    build:
      context: ./
      dockerfile: admin_cost.Dockerfile
    image: ideal97/admin_cost:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/admin_cost
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"

  #######################################################
  # admin_portal: The admin_portal_application microservice
  #######################################################
  admin_portal_application:
    build:
      context: ./
      dockerfile: admin_portal_application.Dockerfile
    image: ideal97/admin_portal_application:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/admin_portal
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"
  
  #######################################################
  # payment: The payment microservice
  #######################################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: ideal97/payment:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/payment
      PYTHONUNBUFFERED: 1
    ports:
      - "5400:5400"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: ideal97/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: ideal97/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # Place application: The Place application microservice
  ###############################################
  place_application:
    build:
      context: ./
      dockerfile: place_application.Dockerfile
    image: ideal97/place_application:esd
    restart: always
    depends_on:
      - application
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      application_URL: http://application:5001/application
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  